"use client";

import { useEffect, useState } from "react";
import { ShieldAlert, AlertTriangle, Search, Filter, Navigation, Info, ArrowRight } from "lucide-react";
import axios from "axios";

export default function AlertsCenter() {
  const [alerts, setAlerts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("Joshimath");
  const [searchFocus, setSearchFocus] = useState(false);

  useEffect(() => {
    const fetchAlerts = async () => {
      try {
        const res = await axios.get("http://localhost:8000/api/dashboard");
        // Convert map data to alerts
        if (res.data.points) {
          const criticalPoints = res.data.points.filter((p: any) => p.risk_level === 'Critical' || p.risk_level === 'High');
          setAlerts(criticalPoints);
        } else if (res.data.wards) {
           const criticalWards = res.data.wards.filter((p: any) => p.risk_level === 'Critical' || p.risk_level === 'High');
           setAlerts(criticalWards);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchAlerts();
  }, []);

  const getSeverityColor = (level: string) => {
    switch (level) {
      case "Critical": return "bg-red-500";
      case "High": return "bg-orange-500";
      case "Moderate": return "bg-yellow-500";
      case "Low": return "bg-green-500";
      default: return "bg-gray-500";
    }
  };

  const getSeverityBg = (level: string) => {
    switch (level) {
      case "Critical": return "bg-red-900/20 border-red-900/50";
      case "High": return "bg-orange-900/20 border-orange-900/50";
      case "Moderate": return "bg-yellow-900/20 border-yellow-900/50";
      case "Low": return "bg-green-900/20 border-green-900/50";
      default: return "bg-gray-900 border-gray-800";
    }
  };

  return (
    <div className="max-w-7xl mx-auto py-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      
      <div className="flex justify-between items-end mb-8">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight flex items-center">
            <ShieldAlert className="w-8 h-8 text-red-500 mr-3" />
            Alerts Center
          </h1>
          <p className="text-gray-400 mt-2 text-sm">Prioritized risk notifications generated by the Random Forest model.</p>
        </div>

        <div className="flex gap-4">
          {/* Autocomplete Mock UI */}
          <div className="relative">
            <div className={`flex items-center bg-gray-900 border ${searchFocus ? 'border-blue-500' : 'border-gray-700'} rounded-lg px-3 py-2 w-72 transition-colors`}>
              <Search className="w-4 h-4 text-gray-500 mr-2" />
              <input 
                type="text" 
                placeholder="Search location..." 
                className="bg-transparent border-none text-white focus:outline-none w-full text-sm"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onFocus={() => setSearchFocus(true)}
                onBlur={() => setTimeout(() => setSearchFocus(false), 200)}
              />
            </div>
            
            {/* Autocomplete Dropdown */}
            {searchFocus && (
              <div className="absolute top-full left-0 w-full mt-2 bg-gray-900 border border-gray-700 rounded-lg shadow-2xl z-50 overflow-hidden">
                 <div className="p-2 space-y-1 text-sm">
                    <div className="px-3 py-2 hover:bg-gray-800 rounded cursor-pointer text-white flex justify-between">
                      <span><strong>Joshimath</strong> (Region)</span>
                      <ArrowRight className="w-4 h-4 text-gray-600"/>
                    </div>
                    <div className="px-3 py-2 hover:bg-gray-800 rounded cursor-pointer text-gray-300 flex justify-between">
                      <span className="pl-4 border-l border-gray-700">Ward 1 (Sub-region)</span>
                      <ArrowRight className="w-4 h-4 text-gray-600"/>
                    </div>
                    <div className="px-3 py-2 hover:bg-gray-800 rounded cursor-pointer text-gray-300 flex justify-between">
                      <span className="pl-8 border-l border-gray-700">District Hospital (Infrastructure)</span>
                      <ArrowRight className="w-4 h-4 text-gray-600"/>
                    </div>
                 </div>
              </div>
            )}
          </div>
          
          <button className="flex items-center bg-gray-900 border border-gray-700 text-gray-300 px-4 py-2 rounded-lg text-sm hover:bg-gray-800 transition-colors">
            <Filter className="w-4 h-4 mr-2" /> Filter
          </button>
        </div>
      </div>

      {/* Severity Legend */}
      <div className="flex space-x-6 mb-8 text-sm bg-gray-900 border border-gray-800 w-max px-4 py-2 rounded-lg shadow-lg">
        <span className="text-gray-400 font-bold uppercase tracking-wider mr-2">Severity:</span>
        <div className="flex items-center text-gray-300"><div className="w-3 h-3 rounded-full bg-red-500 mr-2 shadow-[0_0_10px_rgba(239,68,68,0.5)]"></div> Critical</div>
        <div className="flex items-center text-gray-300"><div className="w-3 h-3 rounded-full bg-orange-500 mr-2 shadow-[0_0_10px_rgba(249,115,22,0.5)]"></div> High</div>
        <div className="flex items-center text-gray-300"><div className="w-3 h-3 rounded-full bg-yellow-500 mr-2 shadow-[0_0_10px_rgba(234,179,8,0.5)]"></div> Moderate</div>
        <div className="flex items-center text-gray-300"><div className="w-3 h-3 rounded-full bg-green-500 mr-2 shadow-[0_0_10px_rgba(34,197,94,0.5)]"></div> Safe</div>
      </div>

      {/* Alerts List */}
      <div className="space-y-4">
        {loading ? (
          <div className="text-gray-500 text-center py-12 animate-pulse font-mono text-sm">Synchronizing Alert Data from Backend...</div>
        ) : alerts.length === 0 ? (
          <div className="text-gray-500 text-center py-12 bg-gray-900/50 rounded-xl border border-gray-800 flex flex-col items-center">
            <div className="w-12 h-12 bg-green-900/20 rounded-full flex items-center justify-center mb-3">
              <div className="w-3 h-3 bg-green-500 rounded-full"></div>
            </div>
            No active critical alerts detected for this region.
          </div>
        ) : (
          alerts.map((alert, idx) => (
            <div key={idx} className={`p-5 rounded-xl border ${getSeverityBg(alert.risk_level)} flex flex-col md:flex-row gap-6 shadow-lg backdrop-blur-sm transition-transform hover:-translate-y-1 hover:shadow-2xl`}>
              
              <div className="flex-1 space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <div className="relative">
                      <div className={`absolute inset-0 rounded-full animate-ping ${getSeverityColor(alert.risk_level)} opacity-20`}></div>
                      <div className={`w-4 h-4 rounded-full ${getSeverityColor(alert.risk_level)}`}></div>
                    </div>
                    <h3 className="text-lg font-bold text-white">Structural Risk Alert — {alert.ward || `Zone ${idx+1}`}</h3>
                  </div>
                  <span className="text-xs text-gray-500 font-mono">12 Jun 2026, 10:34 UTC</span>
                </div>
                
                <p className="text-gray-400 text-sm">
                  Model indicates a highly probable infrastructure risk based on accelerated line-of-sight displacement. 
                  Observed deformation speed is <strong className="text-white">{Math.round(alert.ground_deformation_mm)} mm/year</strong>.
                </p>

                {/* Evidence Panel (Mocked for Alert) */}
                <div className="bg-gray-950 border border-gray-800 rounded p-3 text-xs mt-2">
                  <div className="text-gray-500 uppercase tracking-wider mb-2 font-bold flex items-center">
                    <Info className="w-3 h-3 mr-1"/> Evidence Used
                  </div>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-gray-300">
                    <span className="flex items-center"><div className="w-1.5 h-1.5 rounded-full bg-blue-500 mr-2"></div> Satellite Obs.</span>
                    <span className="flex items-center"><div className="w-1.5 h-1.5 rounded-full bg-blue-500 mr-2"></div> Terrain Slope</span>
                    <span className="flex items-center"><div className="w-1.5 h-1.5 rounded-full bg-blue-500 mr-2"></div> Infrastructure</span>
                    <span className="flex items-center"><div className="w-1.5 h-1.5 rounded-full bg-blue-500 mr-2"></div> Historical Trend</span>
                  </div>
                </div>
              </div>

              <div className="md:w-64 bg-gray-950 p-4 rounded-lg border border-gray-800 flex flex-col justify-between shrink-0">
                <div className="space-y-3 mb-4">
                   <div className="flex justify-between items-center text-sm">
                     <span className="text-gray-500">Coordinates</span>
                     <span className="text-gray-300 font-mono text-xs">{alert.latitude.toFixed(4)}, {alert.longitude.toFixed(4)}</span>
                   </div>
                   <div className="flex justify-between items-center text-sm">
                     <span className="text-gray-500">Confidence</span>
                     <span className="text-white font-bold">{alert.confidence_pct}%</span>
                   </div>
                   <div className="flex justify-between items-center text-sm">
                     <span className="text-gray-500">Recommendation</span>
                     <span className="text-orange-400 font-bold text-xs text-right max-w-[120px]">
                        {alert.risk_level === 'Critical' ? 'Evacuation Warning' : 'Detailed Survey'}
                     </span>
                   </div>
                </div>
                
                <button className="w-full bg-gray-800 hover:bg-gray-700 text-white py-2 rounded text-sm transition-colors flex items-center justify-center">
                  <Navigation className="w-4 h-4 mr-2" /> Locate on Map
                </button>
              </div>

            </div>
          ))
        )}
      </div>

    </div>
  );
}
